name: romenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*            
  - numpy>=1.24,<2.0
  - scipy>=1.10,<1.11
  - tqdm>=4.64
  - pymor=2023.2.0
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - cpuonly                 
  - matplotlib>=3.8,<3.10   
  - pandas>=2.2,<2.4        
  - pip
  - pip:
      - python-dotenv>=1.0  
